version: '3.8'

services:
  mongodb:
    image: mongo:6.0.8
    container_name: mongodb
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u $MONGO_USERNAME -p $MONGO_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

  feed-service:
    image: ${PROJECT_NAME}/${APP_NAME}:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_MAINTENANCE_PORT}:${APP_MAINTENANCE_PORT}
      - ${APP_PORT}:${APP_PORT}
    environment:
      CONFIG_FILE: ./config/docker.yaml
    depends_on:
      mongodb:
        condition: service_healthy
